%YAML:1.0
---
image_width: 640
image_height: 360
camera_name: yoga_laptop_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [ 640.0, 0.0, 319.5, 0.0, 640.0, 179.5, 0.0, 0.0, 1.0 ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 640.0, 0.0, 319.5, 0.0, 0.0, 640.0, 179.5, 0.0, 0.0, 0.0, 1.0, 0.0 ]